apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-test-2
  namespace: quota-test-ns
spec:
  containers:
  - name: quota-mem-cpu-test-2
    image: nginx:1.15
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"      
      requests:
        memory: "700Mi"
        cpu: "400m"
