apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test
spec:
  selector:
    matchLabels:
      app: radish
  replicas: 2
  template:
    metadata:
      labels:
        app: radish
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - radish
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: busybox-test
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  selector:
    matchLabels:
      app: carrot
  replicas: 2
  template:
    metadata:
      labels:
        app: carrot
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - carrot
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - radish
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx-test
        image: nginx:1.15