apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: example
  labels:
    app: nginx_pear
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_pear
  template:
    metadata:
      labels:
        app: nginx_pear
    spec:
      containers:
        - name: nginx-test
          image: nginx:1.15
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"