apiVersion: v1
kind: Pod
metadata:
  name: pear-pod
  labels:
    app: pear
spec:
  containers:
  - name: container01
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  initContainers:
  - name: init01
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo init01 && sleep 2']
  - name: init02
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo init02 && sleep 2']