apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-rc-v2
spec:
  replicas: 3
  selector:
    app: busybox-v2
  template:
    metadata:
      labels:
        app: busybox-v2
    spec:
      containers:
      - name: busybox-host
        image: busybox:latest
        command: ["sleep"]
        args: ["10000"]