// Code generated by "stringer -type=Life"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Human-0]
	_ = x[Dog-1]
	_ = x[Cat-2]
}

const _Life_name = "HumanDogCat"

var _Life_index = [...]uint8{0, 5, 8, 11}

func (i Life) String() string {
	if i < 0 || i >= Life(len(_Life_index)-1) {
		return "Life(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Life_name[_Life_index[i]:_Life_index[i+1]]
}
